### ISSUE TITLE
Failed to create passphrase

### ISSUE THREAD

**Issue by LovingMelody** [ibizaman/pass-ssh#3]
Attempted to generate a key with `pass ssh --ssh-t ed25519` 
Error:
`xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option`

OS: Arch Linux

**Comment by ibizaman** [comment]
Thanks for reporting, I could repoduce this issue. The latest commit should fix it.

**Comment by LovingMelody** [comment]
Seems to be working fine, are you able to do a version bump? I would like to be able to package this for nix.

**Comment by ibizaman** [comment]
Done!
